---
default: 
  scope: node
  http_port: 8002
  dc_name: test_dc_ws
  dg_name: test_dg_ws
  kv_system: consul
  dyndns_url: http://wgetip.com

agent:
  work_path: /opt/agent
  back_path: /opt/backup
  down_path: /opt/download
  temp_path: /opt/temp/agent
  cron_path: /opt/crond
  exec_path: /opt/bin
  pickle_file: /opt/bin/agent.bin

application:
  work_path: /opt/service
  back_path: /opt/backup
  down_path: /opt/download
  temp_path: /opt/temp/application
  cron_path: /opt/crond
  exec_path: /opt/bin
  pickle_file: /opt/bin/application.bin

kv:
  host: 172.17.0.2
  port: 8500
  key: dc/DC_NAME/dg/DG_NAME/KEY

redis:
  host: 192.168.65.2
  port: 6379
  pswd:
  db: 0
  watch: task:DC_NAME:DG_NAME:KEY
  #watchs:
  #  - 
  #    key: upgrade:DC_NAME:DG_NAME:application
  #    func: dg_info
  #    type: application
  #  -
  #    key: upgrade:DC_NAME:DG_NAME:agent
  #    func: dg_agent
  #    type: agent

processes:
  -
    name: http
    file: wshttp
    class: HttpApp
    func: process
    dependent: null
    queue: false
  - 
    name: application
    file: application
    class: Application
    func: process
    dependent: null
    queue: false
  -
    name: agent
    file: agent
    class: Agent
    func: process
    dependent: null
    queue: false
  -
    name: health
    file: health
    class: Health
    func: process
    dependent: application
    queue: false
  -
    name: configure
    file: configure
    class: Configure
    func: process
    dependent: application
    queue: false
  -
    name: crond
    file: crond
    class: Crond
    func: process
    dependent: application
    queue: false

shm:
  running: true
  maintain: false
  status:
    agent:
      intime: normal
      expect: normal
    application:
      intime: normal
      expect: normal
    health:
      intime: normal
      expect: normal
    configure:
      intime: normal
      expect: normal
    crond:
      intime: normal
      expect: normal

logging:
  version: 1
  disable_existing_loggers: false
  formatters: 
    default: 
      format: "[%(asctime)s] [%(process)d] [%(thread)d] [%(filename)20s] [line:%(lineno)4d] [%(levelname)-6s] %(message)s"
  handlers:
    default:
      level: DEBUG
      formatter: default
      class: logging.FileHandler
      encoding: utf8
      filename: /var/log/wspaas/FILE.log
  loggers:
    default:
      handlers: 
        - default
      level: DEBUG
      propagate: false